---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-socks5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-socks5
  name: deployment-socks5-v1
  labels:
    app: socks5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socks5
      version: v1.0.0
  template:
    metadata:
      labels:
        app: socks5
        version: v1.0.0
    spec:
      terminationGracePeriodSeconds: 100
      containers:
      - name: socks5
        image: docker.io/serjs/go-socks5-proxy:latest
        ports:
        - name: c-socks5
          containerPort: 1080
        env:
        - name: PROXY_USER
          value: "pichuang"
        - name: PROXY_PASSWORD
          value: "pichuang"
        - name: PROXY_PORT
          value: "1080"
---
apiVersion: v1
kind: Service
metadata:
  namespace: ns-socks5
  name: svc-socks5
  labels:
    app: socks5
spec:
  type: LoadBalancer
  ports:
  - name: lb-socks5
    port: 1080
    targetPort: c-socks5
  selector:
    app: socks5
