kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc-claim
spec:
  storageClassName: managed-premium-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi