apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest-tracker-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: speed.divecode.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speedtest-tracker
                port:
                  number: 80
